set -e
true
true
/home/andre/rep/bioformatic/assignment_3/software/SPAdes-3.15.5-Linux/bin/spades-core /home/andre/rep/bioformatic/assignment_3/assembly_output/K21/configs/config.info /home/andre/rep/bioformatic/assignment_3/assembly_output/K21/configs/isolate_mode.info
/home/andre/rep/bioformatic/assignment_3/software/SPAdes-3.15.5-Linux/bin/spades-core /home/andre/rep/bioformatic/assignment_3/assembly_output/K33/configs/config.info /home/andre/rep/bioformatic/assignment_3/assembly_output/K33/configs/isolate_mode.info
/home/andre/rep/bioformatic/assignment_3/software/SPAdes-3.15.5-Linux/bin/spades-core /home/andre/rep/bioformatic/assignment_3/assembly_output/K55/configs/config.info /home/andre/rep/bioformatic/assignment_3/assembly_output/K55/configs/isolate_mode.info
/home/andre/rep/bioformatic/assignment_3/software/SPAdes-3.15.5-Linux/bin/spades-core /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/configs/config.info /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/configs/isolate_mode.info
/usr/bin/python3 /home/andre/rep/bioformatic/assignment_3/software/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/scripts/copy_files.py /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/before_rr.fasta /home/andre/rep/bioformatic/assignment_3/assembly_output/before_rr.fasta /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/assembly_graph_after_simplification.gfa /home/andre/rep/bioformatic/assignment_3/assembly_output/assembly_graph_after_simplification.gfa /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/final_contigs.fasta /home/andre/rep/bioformatic/assignment_3/assembly_output/contigs.fasta /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/first_pe_contigs.fasta /home/andre/rep/bioformatic/assignment_3/assembly_output/first_pe_contigs.fasta /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/strain_graph.gfa /home/andre/rep/bioformatic/assignment_3/assembly_output/strain_graph.gfa /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/scaffolds.fasta /home/andre/rep/bioformatic/assignment_3/assembly_output/scaffolds.fasta /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/scaffolds.paths /home/andre/rep/bioformatic/assignment_3/assembly_output/scaffolds.paths /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/assembly_graph_with_scaffolds.gfa /home/andre/rep/bioformatic/assignment_3/assembly_output/assembly_graph_with_scaffolds.gfa /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/assembly_graph.fastg /home/andre/rep/bioformatic/assignment_3/assembly_output/assembly_graph.fastg /home/andre/rep/bioformatic/assignment_3/assembly_output/K77/final_contigs.paths /home/andre/rep/bioformatic/assignment_3/assembly_output/contigs.paths
true
/usr/bin/python3 /home/andre/rep/bioformatic/assignment_3/software/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/andre/rep/bioformatic/assignment_3/assembly_output/scaffolds.fasta --misc_dir /home/andre/rep/bioformatic/assignment_3/assembly_output/misc --threshold_for_breaking_scaffolds 3
true
